/*
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.remoteflags.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.remoteflags.model.UsageRequestsPerMonth;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Usage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Usage {
  public static final String SERIALIZED_NAME_REQUESTS = "requests";
  @SerializedName(SERIALIZED_NAME_REQUESTS)
  private Long requests;

  public static final String SERIALIZED_NAME_REQUESTS_PER_MONTH = "requestsPerMonth";
  @SerializedName(SERIALIZED_NAME_REQUESTS_PER_MONTH)
  private List<UsageRequestsPerMonth> requestsPerMonth = new ArrayList<UsageRequestsPerMonth>();

  public Usage() { 
  }

  public Usage requests(Long requests) {
    
    this.requests = requests;
    return this;
  }

   /**
   * Returned sum of requests
   * @return requests
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Returned sum of requests")

  public Long getRequests() {
    return requests;
  }


  public void setRequests(Long requests) {
    this.requests = requests;
  }


  public Usage requestsPerMonth(List<UsageRequestsPerMonth> requestsPerMonth) {
    
    this.requestsPerMonth = requestsPerMonth;
    return this;
  }

  public Usage addRequestsPerMonthItem(UsageRequestsPerMonth requestsPerMonthItem) {
    this.requestsPerMonth.add(requestsPerMonthItem);
    return this;
  }

   /**
   * Requests per month
   * @return requestsPerMonth
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Requests per month")

  public List<UsageRequestsPerMonth> getRequestsPerMonth() {
    return requestsPerMonth;
  }


  public void setRequestsPerMonth(List<UsageRequestsPerMonth> requestsPerMonth) {
    this.requestsPerMonth = requestsPerMonth;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Usage usage = (Usage) o;
    return Objects.equals(this.requests, usage.requests) &&
        Objects.equals(this.requestsPerMonth, usage.requestsPerMonth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requests, requestsPerMonth);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Usage {\n");
    sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
    sb.append("    requestsPerMonth: ").append(toIndentedString(requestsPerMonth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

