/*
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.remoteflags.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.remoteflags.JSON;

/**
 * UsageRequestInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UsageRequestInner {
  public static final String SERIALIZED_NAME_FLAG_ID = "flagId";
  @SerializedName(SERIALIZED_NAME_FLAG_ID)
  private String flagId;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private String date;

  public static final String SERIALIZED_NAME_FLAG_PROPERTIES = "flagProperties";
  @SerializedName(SERIALIZED_NAME_FLAG_PROPERTIES)
  private Object flagProperties;

  public UsageRequestInner() { 
  }

  public UsageRequestInner flagId(String flagId) {
    
    this.flagId = flagId;
    return this;
  }

   /**
   * Get flagId
   * @return flagId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFlagId() {
    return flagId;
  }


  public void setFlagId(String flagId) {
    this.flagId = flagId;
  }


  public UsageRequestInner date(String date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getDate() {
    return date;
  }


  public void setDate(String date) {
    this.date = date;
  }


  public UsageRequestInner flagProperties(Object flagProperties) {
    
    this.flagProperties = flagProperties;
    return this;
  }

   /**
   * Get flagProperties
   * @return flagProperties
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Object getFlagProperties() {
    return flagProperties;
  }


  public void setFlagProperties(Object flagProperties) {
    this.flagProperties = flagProperties;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageRequestInner usageRequestInner = (UsageRequestInner) o;
    return Objects.equals(this.flagId, usageRequestInner.flagId) &&
        Objects.equals(this.date, usageRequestInner.date) &&
        Objects.equals(this.flagProperties, usageRequestInner.flagProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flagId, date, flagProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageRequestInner {\n");
    sb.append("    flagId: ").append(toIndentedString(flagId)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    flagProperties: ").append(toIndentedString(flagProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("flagId");
    openapiFields.add("date");
    openapiFields.add("flagProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("flagId");
    openapiRequiredFields.add("date");
    openapiRequiredFields.add("flagProperties");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UsageRequestInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (UsageRequestInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsageRequestInner is not found in the empty JSON string", UsageRequestInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UsageRequestInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UsageRequestInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UsageRequestInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("flagId") != null && !jsonObj.get("flagId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `flagId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flagId").toString()));
      }
      if (jsonObj.get("date") != null && !jsonObj.get("date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsageRequestInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsageRequestInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsageRequestInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsageRequestInner.class));

       return (TypeAdapter<T>) new TypeAdapter<UsageRequestInner>() {
           @Override
           public void write(JsonWriter out, UsageRequestInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsageRequestInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UsageRequestInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UsageRequestInner
  * @throws IOException if the JSON string is invalid with respect to UsageRequestInner
  */
  public static UsageRequestInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsageRequestInner.class);
  }

 /**
  * Convert an instance of UsageRequestInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

