/*
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.remoteflags.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsageRequestInner
 */
public class UsageRequestInnerTest {
    private final UsageRequestInner model = new UsageRequestInner();

    /**
     * Model tests for UsageRequestInner
     */
    @Test
    public void testUsageRequestInner() {
        // TODO: test UsageRequestInner
    }

    /**
     * Test the property 'flagId'
     */
    @Test
    public void flagIdTest() {
        // TODO: test flagId
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'flagProperties'
     */
    @Test
    public void flagPropertiesTest() {
        // TODO: test flagProperties
    }

}
