/*
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.remoteflags.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UsageRequestsPerMonth
 */
public class UsageRequestsPerMonthTest {
    private final UsageRequestsPerMonth model = new UsageRequestsPerMonth();

    /**
     * Model tests for UsageRequestsPerMonth
     */
    @Test
    public void testUsageRequestsPerMonth() {
        // TODO: test UsageRequestsPerMonth
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'requests'
     */
    @Test
    public void requestsTest() {
        // TODO: test requests
    }

}
